config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
QC.Doc:
    repos:
      this_repo:
        commands:
        - tox -c tox.ini -e .
        container: qc.doc_dorky-smalt-iguana
timeout: 5400        
QC.Sty:
    repos:
      this_repo:
        commands:
        - flake8 .
        container: qc.sty_droopy-coral-swan
timeout: 5400
QC.Uni:
    repos:
      this_repo:
        commands:
        - pytest . --json-report  --json-report-indent 4
        container: qc.uni_flaky-denim-uguisu
timeout: 5400
