services:
  qc.doc_woolly-ruby-pig:
    command: sleep 6000000
    image: painless/tox@sha256:4f31b329507f9ab658e3c36c5252ad063cabe3d978d6836e0ba322ccb79af060
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
  qc.uni_crappy-taupe-slug:
    command: sleep 6000000
    image: eoscsynergy/sqaaas-micromamba:1.5.3-1
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
